name: Makefile CI

on:
  push:
    branches: [ "master", "goroda-check_actions" ]
  pull_request:
    branches: [ "master", "goroda-check_actions" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: make init

    - name: Run check
      run: make ci
